const data = [
    {
        "slug": "acid-arrow",
        "name": "Acid Arrow",
        "desc": "A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn.",
        "higher_level": "When you cast this spell using a spell slot of 3rd level or higher, the damage (both initial and later) increases by 1d4 for each slot level above 2nd.",
        "page": "phb 259",
        "range": "90 feet",
        "components": "V, S, M",
        "material": "Powdered rhubarb leaf and an adder's stomach.",
        "ritual": "no",
        "duration": "Instantaneous",
        "concentration": "no",
        "casting_time": "1 action",
        "level": "2nd-level",
        "level_int": 2,
        "school": "Evocation",
        "dnd_class": "Druid, Wizard",
        "archetype": "Druid: Swamp",
        "circles": "Swamp",
        "document__slug": "wotc-srd",
        "document__title": "Systems Reference Document",
        "document__license_url": "http://open5e.com/legal"
    },
    {
        "slug": "acid-splash",
        "name": "Acid Splash",
        "desc": "You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a dexterity saving throw or take 1d6 acid damage. This spell's damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).",
        "higher_level": "",
        "page": "phb 211",
        "range": "60 feet",
        "components": "V, S",
        "material": "",
        "ritual": "no",
        "duration": "Instantaneous",
        "concentration": "no",
        "casting_time": "1 action",
        "level": "Cantrip",
        "level_int": 0,
        "school": "Conjuration",
        "dnd_class": "Sorcerer, Wizard",
        "archetype": "",
        "circles": "",
        "document__slug": "wotc-srd",
        "document__title": "Systems Reference Document",
        "document__license_url": "http://open5e.com/legal"
    },
    {
        "slug": "aid",
        "name": "Aid",
        "desc": "Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target's hit point maximum and current hit points increase by 5 for the duration.",
        "higher_level": "When you cast this spell using a spell slot of 3rd level or higher, a target's hit points increase by an additional 5 for each slot level above 2nd.",
        "page": "phb 211",
        "range": "30 feet",
        "components": "V, S, M",
        "material": "A tiny strip of white cloth.",
        "ritual": "no",
        "duration": "8 hours",
        "concentration": "no",
        "casting_time": "1 action",
        "level": "2nd-level",
        "level_int": 2,
        "school": "Abjuration",
        "dnd_class": "Cleric, Paladin",
        "archetype": "",
        "circles": "",
        "document__slug": "wotc-srd",
        "document__title": "Systems Reference Document",
        "document__license_url": "http://open5e.com/legal"
    },
]

export default data;